version: '3.7'
services:
  stunnel:
    build:
      context: ./latest/
    image: appuio/stunnel:latest
    environment:
      CONNECT: ${CONNECT:-stunnel.tld:16379}
      #CONNECT_PORT: "16379"
      #CONNECT_HOST: "stunnel.tld"
      ACCEPT: ${ACCEPT:-0.0.0.0:6379}
      LOG_LEVEL: 7
      CLIENT: "yes"
      CIPHERS: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256

    ports:
      - "6379:6379"
